id: 3c108c55-0c10-495f-8793-35123c340d86
full_slug: public-cloud-kubernetes-backup-restore-pv-volume-snapshot
reference_category: public-cloud-containers-orchestration-managed-kubernetes-k8s-backup-and-restore