language: python
python:
  - "3.5"
install:
  - git clone --recursive https://github.com/ovh/docs-rendering.git
  - pip install -r docs-rendering/requirements.txt

# command to run tests
script:
  - cd docs-rendering && ${PELICAN:-pelican} --debug --settings pelicanconf.py --fatal errors ../pages
