apiVersion: triliovault.trilio.io/v1
kind: BackupPlan
metadata:
  name: mysql-qa-helm-release-backup-plan
  namespace: tvk
spec:
  backupConfig:
    target:
      name: trilio-ovh-s3-target
      namespace: demo-backup-ns
  backupPlanComponents:
    helmReleases:
      - mysql-qa
