apiVersion: triliovault.trilio.io/v1
kind: Target
metadata:
  name: trilio-ovh-s3-target
spec:
  type: ObjectStore
  vendor: Other
  objectStoreCredentials:
    url: "https://s3.bhs.cloud.ovh.net"
    bucketName: "demo-ovh-s3-bucket"
    region: "bhs"
    credentialSecret:
      name: trilio-ovh-s3-target-secret
      namespace: tvk
  thresholdCapacity: 100Gi

