id: 432b57a9-4718-413f-9d27-becaf6036d3c
full_slug: api-domains-landing-page
banner: test-banner
# Given the banner files, we expect banner and footer on fr-fr,
# banner only on fr-ca, and footer only on en-us. Nothing on other languages.
