id: 248ecaf8-ecf4-46e7-967e-c2833a5526ba
full_slug: public-cloud-kubernetes-backing-up-cluster-velero
reference_category: public-cloud-containers-orchestration-managed-kubernetes-k8s-backup-and-restore