id: 13bbea84-7247-4808-999b-b266932385b4
full_slug: public-cloud-kubernetes-backing-up-volumes-stash
reference_category: public-cloud-containers-orchestration-managed-kubernetes-k8s-backup-and-restore