id: ab52b776-0997-4d2b-a562-319cd589bae8
full_slug: public-cloud-kubernetes-backup-restore-cluster-cloudcasa
reference_category: public-cloud-containers-orchestration-managed-kubernetes-k8s-backup-and-restore