id: 19e65c7c-135a-43c8-b0bd-6bb7ae303c55
full_slug: security-specifications-secnumcloud-hosted-private-cloud-vmvare
reference_category: account-and-service-management-account-information-security-and-conformity