id: 53144725-3fd5-4aac-b475-bf8cda18e60d
full_slug: public-cloud-private-registry-responsibility-model
reference_category: public-cloud-containers-orchestration-managed-private-registry-getting-started