id: 6f48125a-2f2b-4717-98f7-45dcc312e96f
full_slug: public-cloud-kubernetes-backup-restore-cluster-trilio
reference_category: public-cloud-containers-orchestration-managed-kubernetes-k8s-backup-and-restore